/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Banco;

/**
 *
 * @author felip
 */
public class TelaUrna extends javax.swing.JFrame {

    /**
     * Creates new form TelaUrna
     */
    public TelaUrna() {
        initComponents();
        lblFim.setVisible(false);
        pnlMotivo.setVisible(false);
        lblNumCand.setVisible(false);
        lblId.setText("" + b.numE);
        Banco top = new Banco();
        top.getNumCand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        pnlJustica = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pnlDigitos = new javax.swing.JPanel();
        pn1 = new javax.swing.JPanel();
        pnl1 = new javax.swing.JLabel();
        pn2 = new javax.swing.JPanel();
        pnl2 = new javax.swing.JLabel();
        pn3 = new javax.swing.JPanel();
        pnl3 = new javax.swing.JLabel();
        pn4 = new javax.swing.JPanel();
        pnl4 = new javax.swing.JLabel();
        pn5 = new javax.swing.JPanel();
        pnl5 = new javax.swing.JLabel();
        pn6 = new javax.swing.JPanel();
        pnl6 = new javax.swing.JLabel();
        pn7 = new javax.swing.JPanel();
        pnl7 = new javax.swing.JLabel();
        pn8 = new javax.swing.JPanel();
        pnl8 = new javax.swing.JLabel();
        pn9 = new javax.swing.JPanel();
        pnl9 = new javax.swing.JLabel();
        pn0 = new javax.swing.JPanel();
        pnl0 = new javax.swing.JLabel();
        pnBranco = new javax.swing.JPanel();
        pnlBranco = new javax.swing.JLabel();
        pnCorrige = new javax.swing.JPanel();
        pnlCorrige = new javax.swing.JLabel();
        pnConfirma = new javax.swing.JPanel();
        pnlConfirma = new javax.swing.JLabel();
        pnTela = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnInfo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnImg = new javax.swing.JPanel();
        pnImagem = new javax.swing.JPanel();
        lblIcone = new javax.swing.JLabel();
        lblIdCand = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnNumeros = new javax.swing.JPanel();
        pnlFim = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTituloPartido = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTituloNome = new javax.swing.JLabel();
        lblTituloNum = new javax.swing.JLabel();
        lblNum1 = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblVotoPara = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblNumCand = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblData = new javax.swing.JLabel();
        pnlMotivo = new javax.swing.JPanel();
        lblMV = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Urna Eletrônica");
        setMinimumSize(new java.awt.Dimension(1040, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(211, 211, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlJustica.setBackground(new java.awt.Color(255, 255, 255));
        pnlJustica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Coat_of_arms_of_Brazil_(grayscale).svg.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel29.setText("JUSTIÇA");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel30.setText("ELEITORAL");

        javax.swing.GroupLayout pnlJusticaLayout = new javax.swing.GroupLayout(pnlJustica);
        pnlJustica.setLayout(pnlJusticaLayout);
        pnlJusticaLayout.setHorizontalGroup(
            pnlJusticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJusticaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnlJusticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJusticaLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJusticaLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(25, 25, 25))))
        );
        pnlJusticaLayout.setVerticalGroup(
            pnlJusticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlJusticaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnlJustica, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 300, 90));

        pnlDigitos.setBackground(new java.awt.Color(51, 51, 51));
        pnlDigitos.setPreferredSize(new java.awt.Dimension(278, 520));

        pn1.setBackground(new java.awt.Color(45, 45, 45));
        pn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn1.setToolTipText("1");
        pn1.setPreferredSize(new java.awt.Dimension(60, 53));
        pn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn1MouseClicked(evt);
            }
        });

        pnl1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl1.setForeground(new java.awt.Color(255, 255, 255));
        pnl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl1.setText("1");
        pnl1.setToolTipText("1");
        pnl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn2.setBackground(new java.awt.Color(45, 45, 45));
        pn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn2.setToolTipText("2");
        pn2.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl2.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl2.setForeground(new java.awt.Color(255, 255, 255));
        pnl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl2.setText("2");
        pnl2.setToolTipText("2");
        pnl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnl2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn2Layout.setVerticalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn3.setBackground(new java.awt.Color(45, 45, 45));
        pn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn3.setToolTipText("3");
        pn3.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl3.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl3.setForeground(new java.awt.Color(255, 255, 255));
        pnl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl3.setText("3");
        pnl3.setToolTipText("3");
        pnl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn3Layout = new javax.swing.GroupLayout(pn3);
        pn3.setLayout(pn3Layout);
        pn3Layout.setHorizontalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn3Layout.setVerticalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn4.setBackground(new java.awt.Color(45, 45, 45));
        pn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn4.setToolTipText("4");
        pn4.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl4.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl4.setForeground(new java.awt.Color(255, 255, 255));
        pnl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl4.setText("4");
        pnl4.setToolTipText("4");
        pnl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn4Layout = new javax.swing.GroupLayout(pn4);
        pn4.setLayout(pn4Layout);
        pn4Layout.setHorizontalGroup(
            pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn4Layout.setVerticalGroup(
            pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn5.setBackground(new java.awt.Color(45, 45, 45));
        pn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn5.setToolTipText("5");
        pn5.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl5.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl5.setForeground(new java.awt.Color(255, 255, 255));
        pnl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl5.setText("5");
        pnl5.setToolTipText("5");
        pnl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn5Layout = new javax.swing.GroupLayout(pn5);
        pn5.setLayout(pn5Layout);
        pn5Layout.setHorizontalGroup(
            pn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn5Layout.setVerticalGroup(
            pn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn6.setBackground(new java.awt.Color(45, 45, 45));
        pn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn6.setToolTipText("6");
        pn6.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl6.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl6.setForeground(new java.awt.Color(255, 255, 255));
        pnl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl6.setText("6");
        pnl6.setToolTipText("6");
        pnl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn6Layout = new javax.swing.GroupLayout(pn6);
        pn6.setLayout(pn6Layout);
        pn6Layout.setHorizontalGroup(
            pn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn6Layout.setVerticalGroup(
            pn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl6, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn7.setBackground(new java.awt.Color(45, 45, 45));
        pn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn7.setToolTipText("7");
        pn7.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl7.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl7.setForeground(new java.awt.Color(255, 255, 255));
        pnl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl7.setText("7");
        pnl7.setToolTipText("7");
        pnl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn7Layout = new javax.swing.GroupLayout(pn7);
        pn7.setLayout(pn7Layout);
        pn7Layout.setHorizontalGroup(
            pn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn7Layout.setVerticalGroup(
            pn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn8.setBackground(new java.awt.Color(45, 45, 45));
        pn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn8.setToolTipText("8");
        pn8.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl8.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl8.setForeground(new java.awt.Color(255, 255, 255));
        pnl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl8.setText("8");
        pnl8.setToolTipText("8");
        pnl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn8Layout = new javax.swing.GroupLayout(pn8);
        pn8.setLayout(pn8Layout);
        pn8Layout.setHorizontalGroup(
            pn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn8Layout.setVerticalGroup(
            pn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn9.setBackground(new java.awt.Color(45, 45, 45));
        pn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn9.setToolTipText("9");
        pn9.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl9.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl9.setForeground(new java.awt.Color(255, 255, 255));
        pnl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl9.setText("9");
        pnl9.setToolTipText("9");
        pnl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn9Layout = new javax.swing.GroupLayout(pn9);
        pn9.setLayout(pn9Layout);
        pn9Layout.setHorizontalGroup(
            pn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn9Layout.setVerticalGroup(
            pn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl9, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pn0.setBackground(new java.awt.Color(45, 45, 45));
        pn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn0.setToolTipText("0");
        pn0.setPreferredSize(new java.awt.Dimension(60, 53));

        pnl0.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        pnl0.setForeground(new java.awt.Color(255, 255, 255));
        pnl0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl0.setText("0");
        pnl0.setToolTipText("0");
        pnl0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl0MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl0MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn0Layout = new javax.swing.GroupLayout(pn0);
        pn0.setLayout(pn0Layout);
        pn0Layout.setHorizontalGroup(
            pn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        pn0Layout.setVerticalGroup(
            pn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl0, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnBranco.setBackground(new java.awt.Color(255, 255, 255));
        pnBranco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnBranco.setToolTipText("Voto em branco");
        pnBranco.setPreferredSize(new java.awt.Dimension(53, 53));

        pnlBranco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pnlBranco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlBranco.setText("BRANCO");
        pnlBranco.setToolTipText("Votar em branco");
        pnlBranco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBrancoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBrancoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnBrancoLayout = new javax.swing.GroupLayout(pnBranco);
        pnBranco.setLayout(pnBrancoLayout);
        pnBrancoLayout.setHorizontalGroup(
            pnBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBranco, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
        pnBrancoLayout.setVerticalGroup(
            pnBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        pnCorrige.setBackground(new java.awt.Color(204, 0, 0));
        pnCorrige.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnCorrige.setToolTipText("Corrigir voto");
        pnCorrige.setAutoscrolls(true);
        pnCorrige.setPreferredSize(new java.awt.Dimension(53, 53));

        pnlCorrige.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pnlCorrige.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlCorrige.setText("CORRIGE");
        pnlCorrige.setToolTipText("Corrigir voto");
        pnlCorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCorrigeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCorrigeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlCorrigeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnCorrigeLayout = new javax.swing.GroupLayout(pnCorrige);
        pnCorrige.setLayout(pnCorrigeLayout);
        pnCorrigeLayout.setHorizontalGroup(
            pnCorrigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCorrige, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
        pnCorrigeLayout.setVerticalGroup(
            pnCorrigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCorrige, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        pnConfirma.setBackground(new java.awt.Color(0, 166, 55));
        pnConfirma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnConfirma.setToolTipText("Confirmar voto");
        pnConfirma.setPreferredSize(new java.awt.Dimension(53, 53));

        pnlConfirma.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pnlConfirma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlConfirma.setText("CONFIRMA");
        pnlConfirma.setToolTipText("Confirmar voto");
        pnlConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlConfirmaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnConfirmaLayout = new javax.swing.GroupLayout(pnConfirma);
        pnConfirma.setLayout(pnConfirmaLayout);
        pnConfirmaLayout.setHorizontalGroup(
            pnConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
        pnConfirmaLayout.setVerticalGroup(
            pnConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConfirma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDigitosLayout = new javax.swing.GroupLayout(pnlDigitos);
        pnlDigitos.setLayout(pnlDigitosLayout);
        pnlDigitosLayout.setHorizontalGroup(
            pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDigitosLayout.createSequentialGroup()
                .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDigitosLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlDigitosLayout.createSequentialGroup()
                                    .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlDigitosLayout.createSequentialGroup()
                                    .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDigitosLayout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(pn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlDigitosLayout.createSequentialGroup()
                                    .addComponent(pn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlDigitosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(pnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDigitosLayout.setVerticalGroup(
            pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDigitosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDigitosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDigitosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(pnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.add(pnlDigitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 300, 390));

        pnTela.setBackground(new java.awt.Color(255, 255, 255));
        pnTela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Aperte a tecla:");

        pnInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout pnInfoLayout = new javax.swing.GroupLayout(pnInfo);
        pnInfo.setLayout(pnInfoLayout);
        pnInfoLayout.setHorizontalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnInfoLayout.setVerticalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setText("CONFIRMA para CONFIRMAR este voto ");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setText("CORRIGE para CORRIGIR este voto");

        pnImg.setBackground(new java.awt.Color(255, 255, 255));

        pnImagem.setBackground(new java.awt.Color(245, 245, 245));
        pnImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnImagem.setPreferredSize(new java.awt.Dimension(154, 204));

        lblIcone.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnImagemLayout = new javax.swing.GroupLayout(pnImagem);
        pnImagem.setLayout(pnImagemLayout);
        pnImagemLayout.setHorizontalGroup(
            pnImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        pnImagemLayout.setVerticalGroup(
            pnImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        lblIdCand.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        lblIdCand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel16.setText("<html>Nº do <br>Candidato</html>");

        javax.swing.GroupLayout pnImgLayout = new javax.swing.GroupLayout(pnImg);
        pnImg.setLayout(pnImgLayout);
        pnImgLayout.setHorizontalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnImgLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnImagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnImgLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdCand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnImgLayout.setVerticalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(lblIdCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblId.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("0");
        lblId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel15.setText("Nº do Eleitor:");

        pnNumeros.setBackground(new java.awt.Color(255, 255, 255));
        pnNumeros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFim.setBackground(new java.awt.Color(255, 255, 255));
        pnlFim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPartido.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblTituloPartido.setText("Partido:");
        jPanel1.add(lblTituloPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        lblPartido.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lblPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 320, 24));

        lblNome.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 320, 24));

        lblTituloNome.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblTituloNome.setText("Nome:");
        jPanel1.add(lblTituloNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        lblTituloNum.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblTituloNum.setText("Número:");
        jPanel1.add(lblTituloNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 41));

        lblNum1.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        lblNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 31, 41));

        lblNum2.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        lblNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 31, 41));

        lblCargo.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jPanel1.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, 26));

        lblVotoPara.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblVotoPara.setText("SEU VOTO PARA");
        jPanel1.add(lblVotoPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblFim.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblFim.setText("FIM");
        jPanel1.add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        javax.swing.GroupLayout pnTelaLayout = new javax.swing.GroupLayout(pnTela);
        pnTela.setLayout(pnTelaLayout);
        pnTelaLayout.setHorizontalGroup(
            pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(pnImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTelaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel14))
                            .addGroup(pnTelaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumCand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );
        pnTelaLayout.setVerticalGroup(
            pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTelaLayout.createSequentialGroup()
                .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTelaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlFim, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))
                            .addGroup(pnTelaLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(pnNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addComponent(lblNumCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTelaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(pnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(13, 13, 13))
        );

        jPanel2.add(pnTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 660, 400));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 1010, 10));

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblData.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 370, 30));

        pnlMotivo.setBackground(new java.awt.Color(211, 211, 211));
        pnlMotivo.setToolTipText(";)");
        pnlMotivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMV.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        pnlMotivo.add(lblMV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        jPanel2.add(pnlMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 150, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1010, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static String data, motivacao, cargo;
    Banco b = new Banco ();
    public void tocarAudio(String nomeAudio) {
        URL url = getClass().getResource(nomeAudio + ".wav");
        AudioClip audio = Applet.newAudioClip(url);
        audio.play();
    }    
    
    public void verificarNum () {
        if (!lblNum1.getText().equals("") && !lblNum2.getText().equals("")) {
            b.mostrarCandidato();
        }
    }
    
    private void pn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn1MouseClicked

    }//GEN-LAST:event_pn1MouseClicked
    
    private void pnl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl1MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl1.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl1.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       }
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl1MouseClicked

    private void pnl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl2MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl2.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl2.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       } 
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl2MouseClicked

    private void pnl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl3MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl3.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl3.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       } 
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl3MouseClicked

    private void pnl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl4MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl4.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl4.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       } 
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl4MouseClicked

    private void pnl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl5MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl5.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl5.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       } 
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl5MouseClicked

    private void pnl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl6MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl6.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl6.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       } 
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl6MouseClicked

    private void pnl7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl7MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl7.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl7.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       } 
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl7MouseClicked

    private void pnl8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl8MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl8.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl8.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       }
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl8MouseClicked

    private void pnl9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl9MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl9.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl9.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       }
       
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl9MouseClicked

    private void pnl0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl0MouseClicked
       String l1 = lblNum1.getText();
       String l2 = lblNum2.getText();
       
       if (!l1.equals("") && l2.equals("")) {
           lblNum2.setText(pnl0.getText());
       } else if (l2.equals("")) {
           lblNum1.setText(pnl0.getText());
       } else if (!l1.equals("") && !l2.equals("")) {
           JOptionPane.showMessageDialog(null, "Atenção: Aperte CORRIGE para corrigir seu voto", "Atenção!" , 3);
       }
      
       verificarNum();
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnl0MouseClicked

    private void pnlBrancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBrancoMouseClicked
       tocarAudio("somTecla");
    }//GEN-LAST:event_pnlBrancoMouseClicked

    private void pnlCorrigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCorrigeMouseClicked
        lblNum1.setText("");
        lblNum2.setText("");
        lblNome.setText("");
        lblPartido.setText("");
        lblIdCand.setText("");
        lblIcone.setIcon(null);
        
        tocarAudio("somTecla");
    }//GEN-LAST:event_pnlCorrigeMouseClicked

    private void pnlConfirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConfirmaMouseClicked
        lblFim.setVisible(true);
        pnInfo.setVisible(false);
        pnImg.setVisible(false);
        lblNum1.setVisible(false);
        lblNum2.setVisible(false);
        lblNome.setVisible(false);
        lblPartido.setVisible(false);
        lblVotoPara.setVisible(false);
        lblCargo.setVisible(false);
        lblTituloNum.setVisible(false);
        lblTituloNome.setVisible(false);
        lblTituloPartido.setVisible(false);
        
        tocarAudio("somConfirma");
        b.confirmarVoto();
    }//GEN-LAST:event_pnlConfirmaMouseClicked

    private void pnlCorrigeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCorrigeMouseExited
    }//GEN-LAST:event_pnlCorrigeMouseExited

    private void pnlCorrigeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCorrigeMouseReleased
        
    }//GEN-LAST:event_pnlCorrigeMouseReleased

    private void pnl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl1MouseExited
        
    }//GEN-LAST:event_pnl1MouseExited

    private void pnl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl3MouseExited
        
    }//GEN-LAST:event_pnl3MouseExited

    private void pnl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl4MouseExited
    }//GEN-LAST:event_pnl4MouseExited

    private void pnl5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl5MouseExited
    }//GEN-LAST:event_pnl5MouseExited

    private void pnl6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl6MouseExited
    }//GEN-LAST:event_pnl6MouseExited

    private void pnl7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl7MouseExited
    }//GEN-LAST:event_pnl7MouseExited

    private void pnl8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl8MouseExited
    }//GEN-LAST:event_pnl8MouseExited

    private void pnl9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl9MouseExited
    }//GEN-LAST:event_pnl9MouseExited

    private void pnl0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl0MouseExited
    }//GEN-LAST:event_pnl0MouseExited

    private void pnlBrancoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBrancoMouseExited
    }//GEN-LAST:event_pnlBrancoMouseExited

    private void pnl2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl2MouseReleased
    }//GEN-LAST:event_pnl2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel lblCargo;
    public static javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblFim;
    public static javax.swing.JLabel lblIcone;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JLabel lblIdCand;
    public static javax.swing.JLabel lblMV;
    public static javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblNum1;
    public static javax.swing.JLabel lblNum2;
    public static javax.swing.JLabel lblNumCand;
    public static javax.swing.JLabel lblPartido;
    public static javax.swing.JLabel lblTituloNome;
    public static javax.swing.JLabel lblTituloNum;
    public static javax.swing.JLabel lblTituloPartido;
    public static javax.swing.JLabel lblVotoPara;
    private javax.swing.JPanel pn0;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn3;
    private javax.swing.JPanel pn4;
    private javax.swing.JPanel pn5;
    private javax.swing.JPanel pn6;
    private javax.swing.JPanel pn7;
    private javax.swing.JPanel pn8;
    private javax.swing.JPanel pn9;
    private javax.swing.JPanel pnBranco;
    private javax.swing.JPanel pnConfirma;
    private javax.swing.JPanel pnCorrige;
    private javax.swing.JPanel pnImagem;
    public static javax.swing.JPanel pnImg;
    public static javax.swing.JPanel pnInfo;
    public static javax.swing.JPanel pnNumeros;
    private javax.swing.JPanel pnTela;
    private javax.swing.JLabel pnl0;
    private javax.swing.JLabel pnl1;
    private javax.swing.JLabel pnl2;
    private javax.swing.JLabel pnl3;
    private javax.swing.JLabel pnl4;
    private javax.swing.JLabel pnl5;
    private javax.swing.JLabel pnl6;
    private javax.swing.JLabel pnl7;
    private javax.swing.JLabel pnl8;
    private javax.swing.JLabel pnl9;
    private javax.swing.JLabel pnlBranco;
    private javax.swing.JLabel pnlConfirma;
    private javax.swing.JLabel pnlCorrige;
    private javax.swing.JPanel pnlDigitos;
    private javax.swing.JPanel pnlFim;
    private javax.swing.JPanel pnlJustica;
    private javax.swing.JPanel pnlMotivo;
    // End of variables declaration//GEN-END:variables
}
